name: interactive_viz
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - zarr
  - xarray
  - geoviews
  - datashader
  - matplotlib
  - panel
  - pandas
  - requests
  - pathlib
  - metpy
  - scipy
  - geopandas
  - streamlit
  - pip
  - pip:
      - sphinx-pythia-theme
